class Jd_phoneItem(scrapy.Item):
    id = scrapy.Field()
    title = scrapy.Field()
    url = scrapy.Field()
    shop_name = scrapy.Field()
    price = scrapy.Field()
    brand = scrapy.Field()
    model = scrapy.Field()
    comment_count = scrapy.Field()
    good_count = scrapy.Field()
    general_count = scrapy.Field()
    poor_count = scrapy.Field()
    show_count = scrapy.Field()
    crawl_date = scrapy.Field()
